services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - scmxpert-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - scmxpert-net

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - scmxpert-net

  producer:
    container_name: kafka-producer
    build:
      context: ./kafka_apps
      dockerfile: Dockerfile.producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - scmxpert-net

  consumer:
    container_name: kafka-consumer
    build:
      context: ./kafka_apps
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka
      - mongodb
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI: mongodb://mongodb:27017
      DB_NAME: scmxpertlite
    networks:
      - scmxpert-net

networks:
  scmxpert-net:
    driver: bridge


